language: php
php:
  - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
cache: apt
install:
    - "sudo apt-get install pandoc"
script: phpunit execute.php
notifications:
    email:
        on_failure: always
