language: php
php:
  - '5.4'
cache: apt
install:
    - "sudo apt-get install pandoc"
script: phpunit "/home/travis/build/Cortiis/ProDocs/execute.php"
notifications:
    email:
        on_failure: always
